import LoadableComponent from './../Loadable/index';
import {
  UserOutlined,
  TagsOutlined,
  AppstoreOutlined,
  InfoCircleOutlined,
  BarcodeOutlined,
  DashboardOutlined,
  EnvironmentOutlined,
  MonitorOutlined,
} from '@ant-design/icons';

export const userRouter: any = [
  {
    path: '/user',
    name: 'user',
    title: 'User',
    component: LoadableComponent(() => import('../../components/Layout/UserLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: '/user/login',
    name: 'login',
    title: 'LogIn',
    component: LoadableComponent(() => import('../../scenes/Login')),
    showInMenu: false,
  },
];

export const appRouters: any = [
  {
    path: '/',
    exact: true,
    name: 'home',
    permission: '',
    title: 'Home',
    component: LoadableComponent(() => import('../../components/Layout/AppLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: '/dashboard',
    name: 'dashboard',
    permission: '',
    title: 'Dashboard',
    icon: DashboardOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Dashboard')),
  },
  {
    path: '/sites',
    name: 'sites',
    permission: '',
    title: 'Sites',
    icon: EnvironmentOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Sites')),
  },
  {
    path: '/scans',
    name: 'scans',
    permission: '',
    title: 'Scans',
    icon: BarcodeOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Scans')),
  },
  {
    path: '/siteshealth',
    name: 'siteshealth',
    permission: '',
    title: 'Sites Health',
    icon: MonitorOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/SitesHealth')),
  },
  {
    path: '/searchbytag',
    name: 'searchScans',
    permission: '',
    title: 'Search By Tag',
    icon: BarcodeOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/SeachByTag')),
  },
  {
    path: '/searchbysite',
    name: 'searchSite',
    permission: '',
    title: 'Search By Site',
    icon: BarcodeOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/SearchBySite')),
  },
  {
    path: '/checktag',
    name: 'checkTag',
    permission: '',
    title: 'Check Tag',
    icon: BarcodeOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/tags/check-tag')),
  },
  {
    path: '/importtag',
    name: 'importTag',
    permission: '',
    title: 'Import Tag',
    icon: BarcodeOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/tags/import-tag')),
  },
  {
    path: '/users',
    permission: 'Pages.Users',
    title: 'Users',
    name: 'user',
    icon: UserOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Users')),
  },
  {
    path: '/roles',
    permission: 'Pages.Roles',
    title: 'Roles',
    name: 'role',
    icon: TagsOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Roles')),
  },
  {
    path: '/tenants',
    permission: 'Pages.Tenants',
    title: 'Tenants',
    name: 'tenant',
    icon: AppstoreOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Tenants')),
  },
  {
    path: '/help',
    permission: '',
    title: 'Help',
    name: 'help',
    icon: InfoCircleOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/About')),
  },
  {
    path: '/logout',
    permission: '',
    title: 'Logout',
    name: 'logout',
    showInMenu: false,
    component: LoadableComponent(() => import('../../components/Logout')),
  },
  {
    path: '/exception?:type',
    permission: '',
    title: 'exception',
    name: 'exception',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Exception')),
  },
];

export const routers = [...userRouter, ...appRouters];
