const fixMytaxServiceInfoData = {
  itr_filling: [
    {
      key: 1,
      name: "ITR-1",
      subSections: null,
      description:
        "Salaried Employee / Pensioner with Income from Other Sources",
      documents: [],
      fee: 1100,
      price: 1298,
      pricingKey: "itr_filling_itr_1",
    },
    {
      key: 2,
      name: "ITR-2",
      subSections: null,
      description:
        "Salaried Employee / Pensioner with Income from Other Sources and House Property Income",
      documents: [],
      fee: 1500,
      price: 1770,
      pricingKey: "itr_filling_itr_2",
    },
    {
      key: 3,
      name: "ITR-3",
      subSections: null,
      description:
        "Salaried Employee / Pensioner with Income from Other Sources, House Property Income & Capital Gain with Shares",
      documents: [],
      fee: 4100,
      price: 2478,
      pricingKey: "itr_filling_itr_3",
    },
    {
      key: 4,
      name: "ITR-4",
      subSections: null,
      description:
        "Assessee with Professional Income and Income from Other Sources",
      documents: [],
      fee: 1500,
      price: 1770,
      pricingKey: "itr_filling_itr_4_1",
    },
    {
      key: 5,
      name: "ITR-4",
      subSections: null,
      description:
        "Assessee with Professional Income as well as House Property and Income from Other Sources",
      documents: [],
      fee: 2100,
      price: 2478,
      pricingKey: "itr_filling_itr_4_2",
    },
    {
      key: 6,
      name: "ITR-4",
      subSections: null,
      description:
        "Assessee with Professional Income as well as House Property, Capital Gain and Income from Other Sources",
      documents: [],
      fee: 4500,
      price: 4838,
      pricingKey: "itr_filling_itr_4_3",
    },
    {
      key: 7,
      name: "ITR-5",
      subSections: null,
      description:
        "NGOs / SOCIETIES / TRUST / CHARITABLE COMPANIES WITHOUT INCOME TAX EXEMPTION APPROVAL",
      documents: [],
      fee: 4100,
      pricingKey: "itr_filling_itr_5",
    },
    {
      key: 8,
      name: "ITR-6",
      subSections: null,
      description: "Company Assessee",
      documents: [],
      fee: 5100,
      pricingKey: "itr_filling_itr_6",
    },
    {
      key: 9,
      name: "ITR-7",
      subSections: null,
      description:
        "NGOs / SOCIETIES / TRUST / CHARITABLE COMPANIES WITH INCOME TAX EXEMPTION APPROVAL",
      documents: [],
      fee: 7100,
    },
    {
      key: 10,
      name: "ITR-U",
      subSections: null,
      description: "CAN BE FILED FOR LAST TWO ASSESSMENT YEARS",
      documents: [],
      fee: 2500,
      pricingKey: "itr_filling_itr_7",
    },
  ],
  tds_filing: [
    {
      key: 1,
      name: "TDS QUARTERLY Statement - 24 - Q1, Q2 & Q3",
      subSections: null,
      description: "",
      documents: [],
      fee: 2100,
      price: 2478,
      pricingKey: "tds_tcs_filing_24_Q1_Q3_1",
    },
    {
      key: 2,
      name: "TDS QUARTERLY Statement - 24 - Q4",
      subSections: null,
      description: "",
      documents: [],
      fee: 4000,
      price: 4720,
      pricingKey: "tds_tcs_filing_24_Q4_2",
    },
    {
      key: 3,
      name: "TDS QUARTERLY Statement - 26 - Q1, Q2, Q3 & Q4",
      subSections: null,
      description: "",
      documents: [],
      fee: 2100,
      price: 2478,
      pricingKey: "tds_tcs_filing_26_Q1_Q4_3",
    },
    {
      key: 4,
      name: "TCS QUARTERLY Statement",
      subSections: null,
      description: "",
      documents: [],
      fee: 2100,
      price: 2478,
      pricingKey: "tds_tcs_filing_quarterly_4",
    },
    {
      key: 5,
      name: "CORRECTION IN TDS / TCS STATEMENTS",
      subSections: null,
      description: "",
      documents: [],
      fee: 1100,
      price: 1298,
      pricingKey: "tds_tcs_filing_correction_5",
    },
    {
      key: 6,
      name: "TDS ON SALE OF PROPERTY -CHALLAN CUM Statement",
      subSections: null,
      description: "",
      documents: [],
      fee: 5100,
      price: 6018,
      pricingKey: "tds_tcs_filing_property_sale_challan_6",
    },
    {
      key: 7,
      name: "REFUND MATTERS FOR EXCESS TDS / TCS DEPOSIT",
      subSections: null,
      description: "",
      documents: [],
      fee: 5100,
      price: 6018,
      pricingKey: "tds_tcs_filing_refund_excess_7",
    },
  ],
  itr_tds_tcs_notice: [
    {
      key: 1,
      name: "131-1A",
      subSections: [
        {
          key: 1,
          name: "REPLY IN RESPONSE TO SUMMON NOTICE",
          subSections: null,
          description: "",
          documents: [],
          fee: 5100,
          price: 6018,
          pricingKey: "itr_tds_tcs_notice_131_1A_1_1",
        },
        {
          key: 2,
          name: "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE",
          subSections: null,
          description: "",
          documents: [],
          fee: 1500,
          price: 1770,
          pricingKey: "itr_tds_tcs_notice_any_1_2",
        },
      ],
      description: "",
      documents: [],
    },
    {
      key: 2,
      name: "133-6",
      subSections: [
        {
          key: 1,
          name: "REPLY IN RESPONSE TO NOTICE (DIRECT RELATED TO ASSESSEE BY A.O.)",
          subSections: null,
          description: "",
          documents: [],
          fee: 3100,
          price: 3658,
          pricingKey: "itr_tds_tcs_notice_133-6_2_1",
        },
        {
          key: 2,
          name: "REPLY IN RESPONSE TO NOTICE (RELATED TO THIRD PARTY INFORMATION / CONFIRMATION)",
          subSections: null,
          description: "",
          documents: [],
          fee: 2100,
          price: 2478,
          pricingKey: "itr_tds_tcs_notice_133-6_2_2",
        },
        {
          key: 3,
          name: "REPLY IN RESPONSE TO NOTICE (RAISED BY ADI OR DI OFFICE)",
          subSections: null,
          description: "",
          documents: [],
          fee: 7100,
          price: 8378,
          pricingKey: "itr_tds_tcs_notice_133-6_2_3",
        },
        {
          key: 4,
          name: "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE",
          subSections: null,
          description: "",
          documents: [],
          fee: 1500,
          price: 1770,
          pricingKey: "itr_tds_tcs_notice_any_1_2",
        },
      ],
      description: "",
      documents: [],
    },
    {
      key: 3,
      name: "142-1",
      subSections: [
        {
          key: 1,
          name: "BUSINESS CLOSED INFORMATION",
          subSections: null,
          description: "",
          documents: [],
          fee: 2100,
          price: 2478,
          pricingKey: "itr_tds_tcs_notice_142-1_3_1",
        },
        {
          key: 2,
          name: "FOR FILING RETURN OF INCOME - RETURN FILED",
          subSections: null,
          description: "",
          documents: [],
          fee: 5100,
          price: 6018,
          pricingKey: "itr_tds_tcs_notice_142-1_3_2",
        },
        {
          key: 3,
          name: "FOR FILING RETURN OF INCOME - RETURN NOT FILED",
          subSections: null,
          description: "",
          documents: [],
          fee: 7100,
          price: 8378,
          pricingKey: "itr_tds_tcs_notice_142-1_3_3",
        },
        {
          key: 4,
          name: "FOR FURNISHING OF DETAILS AS PROVIDED I.E. ACCOUNTS AND DOCUMENTS FOR ASSESSMENT",
          subSections: null,
          description: "",
          documents: [],
          fee: 11000,
          price: 12980,
          pricingKey: "itr_tds_tcs_notice_142-1_3_4",
        },
        {
          key: 5,
          name: "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE",
          subSections: null,
          description: "",
          documents: [],
          fee: 1500,
          price: 1770,
          pricingKey: "itr_tds_tcs_notice_any_1_2",
        },
        {
          key: 6,
          name: "OTHERS NOTICES",
          subSections: null,
          description: "",
          documents: [],
          fee: 11000,
          price: 12980,
          pricingKey: "itr_tds_tcs_notice_other_3_5",
        },
      ],
      description: "",
      documents: [],
    },
    {
      key: 4,
      name: "143(2)",
      subSections: [
        {
          key: 1,
          name: "REPLY FOR COMPLIANCE",
          subSections: null,
          description: "",
          documents: [],
          fee: 3100,
          price: 3658,
          pricingKey: "itr_tds_tcs_notice_143(2)_4_1",
        },

        {
          key: 2,
          name: "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE",
          subSections: null,
          description: "",
          documents: [],
          fee: 1500,
          price: 1770,
          pricingKey: "itr_tds_tcs_notice_any_1_2",
        },
      ],
      description: "",
      documents: [],
    },
    {
      key: 5,
      name: "143-1",
      subSections: [
        {
          key: 1,
          name: "FOR RECTIFICATION OF DEMAND RAISED VIDE INTIMATION 143-1",
          subSections: null,
          description: "",
          documents: [],
          fee: 2100,
          price: 2478,
          pricingKey: "itr_tds_tcs_notice_143-1_5_1",
        },

        {
          key: 2,
          name: "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE",
          subSections: null,
          description: "",
          documents: [],
          fee: 1500,
          price: 1770,
          pricingKey: "itr_tds_tcs_notice_any_1_2",
        },
      ],
      description: "",
      documents: [],
    },
    {
      key: 6,
      name: "144",
      subSections: [
        {
          key: 1,
          name: "REPLY IN RESPONSE TO NOTICE - NOT RESPONDED",
          subSections: null,
          description: "",
          documents: [],
          fee: 11000,
          price: 12980,
          pricingKey: "itr_tds_tcs_notice_144_6_1",
        },
        {
          key: 2,
          name: "REPLY IN RESPONSE TO NOTICE - RESPONDED",
          subSections: null,
          description: "",
          documents: [],
          fee: 7100,
          price: 8378,
          pricingKey: "itr_tds_tcs_notice_144_6_2",
        },
        {
          key: 3,
          name: "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE",
          subSections: null,
          description: "",
          documents: [],
          fee: 1500,
          price: 1770,
          pricingKey: "itr_tds_tcs_notice_any_1_2",
        },
        {
          key: 4,
          name: "OTHERS NOTICES",
          subSections: null,
          description: "",
          documents: [],
          fee: 11000,
          price: 12980,
          pricingKey: "itr_tds_tcs_notice_144_6_3",
        },
      ],
      description: "",
      documents: [],
    },
    {
      key: 7,
      name: "148A",
      subSections: [
        {
          key: 1,
          name: "REPLY IN RESPONSE TO NOTICE",
          subSections: null,
          description: "",
          documents: [],
          fee: 21000,
          price: 24780,
          pricingKey: "itr_tds_tcs_notice_148A_7_1",
        },

        {
          key: 2,
          name: "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE",
          subSections: null,
          description: "",
          documents: [],
          fee: 1500,
          price: 1770,
          pricingKey: "itr_tds_tcs_notice_any_1_2",
        },
      ],
      description: "",
      documents: [],
    },
    {
      key: 8,
      name: "156",
      subSections: [
        {
          key: 1,
          name: "REPLY IN RESPONSE TO NOTICE",
          subSections: null,
          description: "",
          documents: [],
          fee: 1100,
          price: 1298,
          pricingKey: "itr_tds_tcs_notice_156_8_1",
        },

        {
          key: 2,
          name: "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE",
          subSections: null,
          description: "",
          documents: [],
          fee: 1500,
          price: 1770,
          pricingKey: "itr_tds_tcs_notice_any_1_2",
        },
      ],
      description: "",
      documents: [],
    },
    {
      key: 9,
      name: "176 - 3",
      subSections: [
        {
          key: 1,
          name: "INTIMATION FOR DISCONTINUATION OF BUSINESS",
          subSections: null,
          description: "",
          documents: [],
          fee: 5100,
          price: 6018,
          pricingKey: "itr_tds_tcs_notice_176-3_9_1",
        },

        {
          key: 2,
          name: "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE",
          subSections: null,
          description: "",
          documents: [],
          fee: 1500,
          price: 1770,
          pricingKey: "itr_tds_tcs_notice_any_1_2",
        },
      ],
      description: "",
      documents: [],
    },
    {
      key: 10,
      name: "210 - 3",
      subSections: [
        {
          key: 1,
          name: "REPLY FOR DEPOSIT OF ADVANCE TAX",
          subSections: null,
          description: "",
          documents: [],
          fee: 2100,
          price: 2478,
          pricingKey: "itr_tds_tcs_notice_210-3_10_1",
        },
        {
          key: 2,
          name: "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE",
          subSections: null,
          description: "",
          documents: [],
          fee: 1500,
          price: 1770,
          pricingKey: "itr_tds_tcs_notice_any_1_2",
        },
      ],
      description: "",
      documents: [],
    },
    {
      key: 11,
      name: "221",
      subSections: [
        {
          key: 1,
          name: "REPLY IN RESPONSE TO NOTICE",
          subSections: null,
          description: "",
          documents: [],
          fee: 5100,
          price: 6018,
          pricingKey: "itr_tds_tcs_notice_221_11_1",
        },
        {
          key: 2,
          name: "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE",
          subSections: null,
          description: "",
          documents: [],
          fee: 1500,
          price: 1770,
          pricingKey: "itr_tds_tcs_notice_any_1_2",
        },
      ],
      description: "",
      documents: [],
    },
    {
      key: 12,
      name: "245",
      subSections: [
        {
          key: 1,
          name: "REPLY IN RESPONSE TO NOTICE - SIMPLE REPLY",
          subSections: null,
          description: "",
          documents: [],
          fee: 2100,
          price: 2478,
          pricingKey: "itr_tds_tcs_notice_245_12_1",
        },
        {
          key: 2,
          name: "REPLY IN RESPONSE TO NOTICE - EARLIER DEMAND ADJUSTED WITH REFUND",
          subSections: null,
          description: "",
          documents: [],
          fee: 5100,
          price: 6018,
          pricingKey: "itr_tds_tcs_notice_245_12_2",
        },
        {
          key: 3,
          name: "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE",
          subSections: null,
          description: "",
          documents: [],
          fee: 1500,
          price: 1770,
          pricingKey: "itr_tds_tcs_notice_any_1_2",
        },
        {
          key: 4,
          name: "OTHERS NOTICES",
          subSections: null,
          description: "",
          documents: [],
          fee: 7100,
          price: 8378,
          pricingKey: "itr_tds_tcs_notice_245_12_3",
        },
      ],
      description: "",
      documents: [],
    },
    {
      key: 13,
      name: "271-1-c",
      subSections: [
        {
          key: 1,
          name: "REPLY IN RESPONSE TO NOTICE - APPEAL NOT FILED",
          subSections: null,
          description: "",
          documents: [],
          fee: 11000,
          price: 12980,
          pricingKey: "itr_tds_tcs_notice_271-1-c_13_1",
        },
        {
          key: 2,
          name: "REPLY IN RESPONSE TO NOTICE - APPEAL FILED",
          subSections: null,
          description: "",
          documents: [],
          fee: 8100,
          price: 9558,
          pricingKey: "itr_tds_tcs_notice_271-1-c_13_2",
        },
        {
          key: 3,
          name: "OTHERS NOTICES",
          subSections: null,
          description: "",
          documents: [],
          fee: 11000,
          price: 12980,
          pricingKey: "itr_tds_tcs_notice_271-1-c_13_3",
        },
      ],
      description: "",
      documents: [],
    },
    {
      key: 14,
      name: "NOTICE UNDER OTHER SECTIONS",
      subSections: [
        {
          key: 1,
          name: "NOTICES UNDER OTHER SECTIONS",
          subSections: null,
          description: "",
          documents: [],
          fee: 5100,
          price: 6018,
          pricingKey: "itr_tds_tcs_notice_other_sections_14_1",
        },
      ],
      description: "",
      documents: [],
    },
  ],
  gst_notice: [
    {
      key: 1,
      name: "GST REG-03 (Notice issued for further information / clarification in response to application for new registration or amendment of GST registration certificate.)",
      subSections: null,
      description:
        "Notice issued for further information / clarification in response to application for new registration or amendment of GST registration certificate.",
      documents: [],
      fee: 1100,
      price: 1298,
      pricingKey: "gst_notice_REG_03_1",
    },
    {
      key: 2,
      name: "GST REG-17 (Show Cause Notice as to why GST registration be not be cancelled.)",
      subSections: null,
      description:
        "Show Cause Notice as to why GST registration be not be cancelled.",
      documents: [],
      fee: 2100,
      price: 2478,
      pricingKey: "gst_notice_REG_17_2",
    },
    {
      key: 3,
      name: "GST REG-23 (Show Cause Notice as to why registration of GST cancellation be revoked.)",
      subSections: null,
      description:
        "Show Cause Notice as to why registration of GST cancellation be revoked.",
      documents: [],
      fee: 2100,
      price: 2478,
      pricingKey: "gst_notice_REG_23_3",
    },
    {
      key: 4,
      name: "GST REG-27 (Notice where application for provisional registration has not been made for migration into GST from VAT regime or incomplete details have been provided.)",
      subSections: null,
      description:
        "Notice where application for provisional registration has not been made for migration into GST from VAT regime or incomplete details have been provided.",
      documents: [],
      fee: 1100,
      price: 1298,
      pricingKey: "gst_notice_REG_27_4",
    },
    {
      key: 5,
      name: "GST GSTR-3A (Notice to assessee who are default for not filing GST Returns in GSTR-1 or GSTR-3B or GSTR-4 or GSTR-8.)",
      subSections: null,
      description:
        "Notice to assessee who are default for not filing GST Returns in GSTR-1 or GSTR-3B or GSTR-4 or GSTR-8.",
      documents: [],
      fee: 2100,
      price: 2478,
      pricingKey: "gst_notice_GSTR_3A_5",
    },
    {
      key: 6,
      name: "GST CMP-05 (Show Cause Notice for eligibility to be a composition dealer.)",
      subSections: null,
      description:
        "Show Cause Notice for eligibility to be a composition dealer.",
      documents: [],
      fee: 2100,
      price: 2478,
      pricingKey: "gst_notice_CMP_05_6",
    },
    {
      key: 7,
      name: "GST PCT-03 (Show Cause Notice for misconduct by GST practitioner.)",
      subSections: null,
      description:
        "Assessee with Professional Income as well as House Property and Income from Other SourcesAssessee with Professional Income as well as House Property and Income from Other SourcesShow Cause Notice for misconduct by GST practitioner.",
      documents: [],
      fee: 2100,
      price: 2478,
      pricingKey: "gst_notice_PCT_03_7",
    },
    {
      key: 8,
      name: "GST RFD-08 (Show Cause Notice on rejection of GST refund made.)",
      subSections: null,
      description: "Show Cause Notice on rejection of GST refund made.",
      documents: [],
      fee: 5100,
      price: 6018,
      pricingKey: "gst_notice_RFD_08_8",
    },
    {
      key: 9,
      name: "GST ASMT-02 (Clarification / Additional documents required for provisional assessment.)",
      subSections: null,
      description:
        "Clarification / Additional documents required for provisional assessment.",
      documents: [],
      fee: 5100,
      price: 6018,
      pricingKey: "gst_notice_ASMT_02_9",
    },
    {
      key: 10,
      name: "GST ASMT-06 (Clarification / Additional documents required for final assessment.)",
      subSections: null,
      description:
        "Clarification / Additional documents required for final assessment.",
      documents: [],
      fee: 11000,
      price: 12980,
      pricingKey: "gst_notice_ASMT_06_10",
    },
    {
      key: 11,
      name: "GST ASMT-10 (For intimation of discrepancies in the GST Return after scrutiny.)",
      subSections: null,
      description:
        "For intimation of discrepancies in the GST Return after scrutiny.",
      documents: [],
      fee: 21000,
      price: 24780,
      pricingKey: "gst_notice_ASMT_10_11",
    },
    {
      key: 12,
      name: "GST ASMT-14 (Show Cause Notice under Section 63 for Best Judgment Assessment.)",
      subSections: null,
      description:
        "Show Cause Notice under Section 63 for Best Judgment Assessment.",
      documents: [],
      fee: 7100,
      price: 8378,
      pricingKey: "gst_notice_ASMT_14_12",
    },
    {
      key: 13,
      name: "GST ADT-01 (Notice from the Authorities for conducting Audit under Section 65.)",
      subSections: null,
      description:
        "Notice from the Authorities for conducting Audit under Section 65.",
      documents: [],
      fee: 7100,
      price: 8378,
      pricingKey: "gst_notice_ADT_01_13",
    },
    {
      key: 14,
      name: "GST RVN-01 (Notice under Section 108 issued by the Revisional Authority in case of Revision.)",
      subSections: null,
      description:
        "Notice under Section 108 issued by the Revisional Authority in case of Revision.",
      documents: [],
      fee: 5100,
      price: 6018,
      pricingKey: "gst_notice_RVN_01_14",
    },
    {
      key: 15,
      name: "GST DRC-01 (Show Cause Notice for tax demanded in GST DRC-02.)",
      subSections: null,
      description: "Show Cause Notice for tax demanded in GST DRC-02.",
      documents: [],
      fee: 2100,
      price: 2478,
      pricingKey: "gst_notice_DRC_01_15",
    },
    {
      key: 16,
      name: "GST DRC-10 (Notice for auction of Goods under Section 79(1)(b).)",
      subSections: null,
      description: "Notice for auction of Goods under Section 79(1)(b).",
      documents: [],
      fee: 21000,
      price: 24780,
      pricingKey: "gst_notice_DRC_10_16",
    },
    {
      key: 17,
      name: "GST DRC-11 (Notice to the successful bidder.)",
      subSections: null,
      description: "Notice to the successful bidder.",
      documents: [],
      fee: 5100,
      price: 6018,
      pricingKey: "gst_notice_DRC_11_17",
    },
    {
      key: 18,
      name: "GST DRC-13 (Notice under Section 79(1)(c) to the third person directing to deposit the amount specified.)",
      subSections: null,
      description:
        "Notice under Section 79(1)(c) to the third person directing to deposit the amount specified.",
      documents: [],
      fee: 5100,
      price: 6018,
      pricingKey: "gst_notice_DRC_13_18",
    },
    {
      key: 19,
      name: "GST DRC-16 (Notice under Section 79 for attachment and sale of movable / immovable goods & shares.)",
      subSections: null,
      description:
        "Notice under Section 79 for attachment and sale of movable / immovable goods & shares.",
      documents: [],
      fee: 21000,
      price: 24780,
      pricingKey: "gst_notice_DRC_16_19",
    },
    {
      key: 20,
      name: "ANY OTHER NOTICE",
      subSections: null,
      description: "others",
      documents: [],
      fee: 5100,
      price: 6018,
      pricingKey: "gst_notice_any_20",
    },
  ],
  tax_appeal: [
    {
      key: 1,
      name: "Income Tax Appeal",
      subSections: [
        {
          key: 1,
          name: "FORM - 35 - FILING",
          subSections: null,
          description: "",
          documents: [],
          fee: 7100,
          price: 8378,
          pricingKey: "appeal_income_tax_35_filling_1_1",

        },
        {
          key: 2,
          name: "FORM - 35 - SUBSEQUENT WRITTEN SUBMISSIONS",
          subSections: null,
          description: "",
          documents: [],
          fee: 15000,
          price: 17700,
          pricingKey: "appeal_income_tax_35_subsequent_written_1_2",
        },
        {
          key: 3,
          name: "FORM - 35 - FILING WITH WRITTEN SUBMISSIONS",
          subSections: null,
          description: "",
          documents: [],
          fee: 21000,
          price: 24780,
          pricingKey: "appeal_income_tax_35_filling_written_1_3",
        },
        {
          key: 4,
          name: "FORM - 36 - FILING",
          subSections: null,
          description: "",
          documents: [],
          fee: 11000,
          price: 12980,
          pricingKey: "appeal_income_tax_36_filling_1_4",
        },
        {
          key: 5,
          name: "FORM - 36 - SUBSEQUENT WRITTEN SUBMISSIONS",
          subSections: null,
          description: "",
          documents: [],
          fee: 25000,
          price: 29500,
          pricingKey: "appeal_income_tax_36_subsequent_written_1_5",
        },
        {
          key: 6,
          name: "FORM - 36 - FILING WITH WRITTEN SUBMISSIONS",
          subSections: null,
          description: "",
          documents: [],
          fee: 31000,
          price: 36580,
          pricingKey: "appeal_income_tax_36_filling_written_1_6",
        },
        {
          key: 7,
          name: "PERSONAL HEARING THROUGH AR - OTHER THAN FEE: EXPENSES TO BE REIMBURSED AT ACTUALS",
          subSections: null,
          description: "",
          documents: [],
          fee: 21000,
          price: 24780,
          pricingKey: "appeal_income_tax_personal_actuals_1_7",
        },
      ],
      description: "",
      documents: [],
    },
    {
      key: 2,
      name: "GST Appeal",
      subSections: [
        {
          key: 1,
          name: "FORM - APL-01 - FILING",
          subSections: null,
          description: "",
          documents: [],
          fee: 1500,
          price: 1770,
          pricingKey: "appeal_gst_01_filling_2_1",
        },
        {
          key: 2,
          name: "FORM - APL-01 - SUBSEQUENT WRITTEN SUBMISSIONS",
          subSections: null,
          description: "",
          documents: [],
          fee: 7100,
          price: 8378,
          pricingKey: "appeal_gst_01_subsequent_written_2_2",
        },
        {
          key: 3,
          name: "FORM - APL-01 - FILING WITH WRITTEN SUBMISSIONS",
          subSections: null,
          description: "",
          documents: [],
          fee: 15000,
          price: 17700,
          pricingKey: "appeal_gst_01_filling_written_2_3",
        },
        {
          key: 4,
          name: "FORM - APL-05 - FILING",
          subSections: null,
          description: "",
          documents: [],
          fee: 21000,
          price: 24780,
          pricingKey: "appeal_gst_05_filling_2_4",
        },
        {
          key: 5,
          name: "FORM - APL-05 - SUBSEQUENT WRITTEN SUBMISSIONS",
          subSections: null,
          description: "",
          documents: [],
          fee: 11000,
          price: 12980,
          pricingKey: "appeal_gst_05_subsequent_written_2_5",
        },
        {
          key: 6,
          name: "FORM - APL-05 - FILING WITH WRITTEN SUBMISSIONS",
          subSections: null,
          description: "",
          documents: [],
          fee: 25000,
          price: 29500,
          pricingKey: "appeal_gst_05_filling_written_2_6",
        },
        {
          key: 7,
          name: "PERSONAL HEARING THROUGH AR-OTHER THAN FEE: EXPENSES TO BE REIMBURSED AT ACTUALS",
          subSections: null,
          description: "",
          documents: [],
          fee: 21000,
          price: 24780,
          pricingKey: "appeal_gst_personal_ITAT_actuals_2_7",
        },
      ],
      description: "",
      documents: [],
    },
  ],

  business_consultation: [
    {
      key: 1,
      name: "Enjoy knowledge about intricacies of taxation laws as per Statute",
      subSections: null,
      description: "",
      documents: [],
      fee: 2100,
      pricingKey: "business_consultation_taxation_laws_1",
    },
    {
      key: 2,
      name: "Legal opinion on any complex taxation matters from our Team of Qualified Professionals @ Legal Consultancy",
      subSections: null,
      description: "",
      documents: [],
      fee: 5100,
      price: 6018,
      pricingKey: "business_consultation_taxation_complex_2",
    },
    {
      key: 3,
      name: "Any Business Related Consultancy  Being Proprietorship / Partnership / LLP Or Company",
      subSections: null,
      description: "",
      documents: [],
      fee: 2100,
      price: 2478,
      pricingKey: "business_consultation_related_llp_3",
    },
    {
      key: 4,
      name: "Any NGO Related Consultancy Being Society / Trust / Charitable Company",
      subSections: null,
      description: "",
      documents: [],
      fee: 2100,
      price: 2478,
      pricingKey: "business_consultation_ngo_consultancy_4",
    },
    {
      key: 5,
      name: "Any NGO Income Related Query",
      subSections: null,
      description: "",
      documents: [],
      fee: 2100,
      price: 2478,
      pricingKey: "business_consultation_ngo_income_5",
    },
  ],
};

const fixMytaxServicesInfo = {
  notice: {
    "131-1A": {
      subSections: {
        "REPLY IN RESPONSE TO SUMMON NOTICE": {
          fee: 5100,
          price: 6018,
        },
        "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE": {
          fee: 1500,
          price: 1770,
        },
      },
      description: "",
    },
    "133-6": {
      subSections: {
        "REPLY IN RESPONSE TO NOTICE (DIRECT RELATED TO ASSESSEE BY A.O.)": {
          fee: 3100,
          price: 3658,
        },
        "REPLY IN RESPONSE TO NOTICE (RELATED TO THIRD PARTY INFORMATION / CONFIRMATION)":
          {
            fee: 2100,
            price: 2478,
          },
        "REPLY IN RESPONSE TO NOTICE (RAISED BY ADI OR DI OFFICE)": {
          fee: 7100,
          price: 8378,
        },
        "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE": {
          fee: 1500,
          price: 1770,
        },
      },
      description: "",
    },
    "142-1": {
      subSections: {
        "BUSINESS CLOSED INFORMATION": {
          fee: 2100,
          price: 2478,
        },
        "FOR FILING RETURN OF INCOME - RETURN FILED": {
          fee: 5100,
          price: 6018,
        },
        "FOR FILING RETURN OF INCOME - RETURN NOT FILED": {
          fee: 7100,
          price: 8378,
        },
        "FOR FURNISHING OF DETAILS AS PROVIDED I.E. ACCOUNTS AND DOCUMENTS FOR ASSESSMENT":
          {
            fee: 11000,
            price: 12980,
          },
        "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE": {
          fee: 1500,
          price: 1770,
        },
        "OTHERS NOTICES": {
          fee: 11000,
          price: 12980,
        },
      },
      description: "",
    },
    "143(2)": {
      subSections: {
        "REPLY FOR COMPLIANCE": {
          fee: 3100,
          price: 3658,
        },
        "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE": {
          fee: 1500,
          price: 1770,
        },
      },
      description: "",
    },
    "143-1": {
      subSections: {
        "FOR RECTIFICATION OF DEMAND RAISED VIDE INTIMATION 143-1": {
          fee: 2100,
          price: 2478,
        },
        "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE": {
          fee: 1500,
          price: 1770,
        },
      },
      description: "",
    },
    144: {
      subSections: {
        "REPLY IN RESPONSE TO NOTICE - NOT RESPONDED": {
          // fee: 11000,
          price: 12980,
        },
        "REPLY IN RESPONSE TO NOTICE - RESPONDED": {
          fee: 7100,
          price: 8378,
        },
        "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE": {
          fee: 1500,
          price: 1770,
        },
        "OTHERS NOTICES": {
          fee: 11000,
          price: 12980,
        },
      },
      description: "",
    },
    "148A": {
      subSections: {
        "REPLY IN RESPONSE TO NOTICE": {
          fee: 21000,
          price: 24780,
        },
        "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE": {
          fee: 1500,
          price: 1770,
        },
      },
      description: "",
    },
    156: {
      subSections: {
        "REPLY IN RESPONSE TO NOTICE": {
          fee: 1100,
          price: 1298,
        },
        "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE": {
          fee: 1500,
          price: 1770,
        },
      },
      description: "",
    },
    "176 - 3": {
      subSections: {
        "INTIMATION FOR DISCONTINUATION OF BUSINESS": {
          fee: 5100,
          price: 6018,
        },
        "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE": {
          fee: 1500,
          price: 1770,
        },
      },
      description: "",
    },
    "210 - 3": {
      subSections: {
        "REPLY FOR DEPOSIT OF ADVANCE TAX": {
          fee: 2100,
          price: 2478,
        },
        "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE": {
          fee: 1500,
          price: 1770,
        },
      },
      description: "",
    },
    221: {
      subSections: {
        "REPLY IN RESPONSE TO NOTICE": {
          fee: 5100,
          price: 6018,
        },
        "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE": {
          fee: 1500,
          price: 1770,
        },
      },
      description: "",
    },
    245: {
      subSections: {
        "REPLY IN RESPONSE TO NOTICE - SIMPLE REPLY": {
          fee: 2100,
          price: 2478,
        },
        "REPLY IN RESPONSE TO NOTICE - EARLIER DEMAND ADJUSTED WITH REFUND": {
          fee: 5100,
          price: 6018,
        },
        "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE": {
          fee: 1500,
          price: 1770,
        },
        "OTHERS NOTICES": {
          fee: 7100,
          price: 8378,
        },
      },
      description: "",
    },
    "271-1-c": {
      subSections: {
        "REPLY IN RESPONSE TO NOTICE - APPEAL NOT FILED": {
          fee: 11000,
          price: 12980,
        },
        "REPLY IN RESPONSE TO NOTICE - APPEAL FILED": {
          fee: 8100,
          price: 9558,
        },
        "OTHERS NOTICES": {
          fee: 11000,
          price: 12980,
        },

        "ADJOURNMENT APPLICATION FOR ANY GENUINE CASE": {
          fee: 1500,
          price: 1770,
        },
      },
      description: "",
    },
    "NOTICE UNDER OTHER SECTIONS": {
      subSections: {
        "NOTICES UNDER OTHER SECTIONS": {
          fee: 5100,
          price: 6018,
        },
      },
      description: "",
    },
    others: {
      subSections: {
        "FORM - 35 - FILING": {
          fee: 7100,
          price: 8378,
        },
        "FORM - 35 - SUBSEQUENT WRITTEN SUBMISSIONS": {
          fee: 15000,
          price: 17700,
        },
        "FORM - 35 - FILING WITH WRITTEN SUBMISSIONS": {
          fee: 21000,
          price: 24780,
        },
        "FORM - 36 - FILING": {
          fee: 11000,
          price: 12980,
        },
        "FORM - 36 - SUBSEQUENT WRITTEN SUBMISSIONS": {
          fee: 25000,
          price: 29500,
        },
        "FORM - 36 - FILING WITH WRITTEN SUBMISSIONS": {
          FileSystem: 31000,
          price: 36580,
        },
      },
      description: "",
    },
  },
  gst: {
    "GST REG-03": {
      subSections: null,
      description:
        "Notice issued for further information / clarification in response to application for new registration or amendment of GST registration certificate.",
      dcouments: [],
      fee: 1100,
      price: 1298,
    },
    "GST REG-17": {
      subSections: null,
      description:
        "Show Cause Notice as to why GST registration be not be cancelled.",
      dcouments: [],
      fee: 2100,
      price: 2478,
    },
    "GST REG-23": {
      subSections: null,
      description:
        "Show Cause Notice as to why registration of GST cancellation be revoked.",
      dcouments: [],
      fee: 2100,
      price: 2478,
    },
    "GST REG-27": {
      subSections: null,
      description:
        "Notice where application for provisional registration has not been made for migration into GST from VAT regime or incomplete details have been provided.",
      dcouments: [],
      fee: 1100,
      price: 1298,
    },
    "GST GSTR-3A": {
      subSections: null,
      description:
        "Notice to assessee who are default for not filing GST Returns in GSTR-1 or GSTR-3B or GSTR-4 or GSTR-8.",
      dcouments: [],
      fee: 2100,
      price: 2478,
    },
    "GST CMP-05": {
      subSections: null,
      description:
        "Show Cause Notice for eligibility to be a composition dealer.",
      dcouments: [],
      fee: 2100,
      price: 2478,
    },
    "GST PCT-03": {
      subSections: null,
      description: "Show Cause Notice for misconduct by GST practitioner.",
      dcouments: [],
      fee: 2100,
      price: 2478,
    },
    "GST RFD-08": {
      subSections: null,
      description: "Show Cause Notice on rejection of GST refund made.",
      dcouments: [],
      fee: 5100,
      price: 6018,
    },
    "GST ASMT-02": {
      subSections: null,
      description:
        "Clarification / Additional documents required for provisional assessment.",
      dcouments: [],
      fee: 5100,
      price: 6018,
    },
    "GST ASMT-06": {
      subSections: null,
      description:
        "Clarification / Additional documents required for final assessment.",
      dcouments: [],
      fee: 11000,
      price: 12980,
    },
    "GST ASMT-10": {
      subSections: null,
      description:
        "For intimation of discrepancies in the GST Return after scrutiny.",
      dcouments: [],
      fee: 21000,
      price: 24780,
    },
    "GST ASMT-14": {
      subSections: null,
      description:
        "Show Cause Notice under Section 63 for Best Judgment Assessment.",
      dcouments: [],
      fee: 7100,
      price: 8378,
    },
    "GST ADT-01": {
      subSections: null,
      description:
        "Notice from the Authorities for conducting Audit under Section 65.",
      dcouments: [],
      fee: 7100,
      price: 8378,
    },
    "GST RVN-01": {
      subSections: null,
      description:
        "Notice under Section 108 issued by the Revisional Authority in case of Revision.",
      dcouments: [],
      fee: 5100,
      price: 6018,
    },
    "GST DRC-01": {
      subSections: null,
      description: "Show Cause Notice for tax demanded in GST DRC-02.",
      dcouments: [],
      fee: 2100,
      price: 2478,
    },
    "GST DRC-10": {
      subSections: null,
      description: "	Notice for auction of Goods under Section 79(1)(b).",
      dcouments: [],
      fee: 21000,
      price: 24780,
    },
    "GST DRC-11": {
      subSections: null,
      description: "Notice to the successful bidder.",
      dcouments: [],
      fee: 5100,
      price: 6018,
    },
    "GST DRC-13": {
      subSections: null,
      description:
        "Notice under Section 79(1)(c) to the third person directing to deposit the amount specified.",
      dcouments: [],
      fee: 5100,
      price: 6018,
    },
    "GST DRC-16": {
      subSections: null,
      description:
        "Notice under Section 79 for attachment and sale of movable / immovable goods & shares.",
      dcouments: [],
      fee: 21000,
      price: 24780,
    },
    "ANY OTHER NOTICE": {
      subSections: null,
      description: "",
      dcouments: [],
      fee: 5100,
      price: 6018,
    },
  },
  consultation: {
    "Visitors may enjoy knowledge about intricacies of taxation laws as per Statute":
      {
        subSections: null,
        description: "",
        dcouments: [],
        fee: 2500,
        price: 2950,
      },
    "Visitors may seek legal opinion on any complex taxation matters from our Team of Qualified Professionals @ Legal Consultancy":
      {
        subSections: null,
        description: "",
        dcouments: [],
        fee: 5100,
        price: 6018,
      },
    "ANY BUSINESS RELATED CONSULTANCY  BEING PROPRIETORSHIP / PARTNERSHIP / LLP OR COMPANY":
      {
        subSections: null,
        description: "",
        dcouments: [],
        fee: 2100,
        price: 2478,
      },
    "ANY NGO RELATED CONSULTANCY BEING SOCIETY / TRUST / CHARITABLE COMPANY": {
      subSections: null,
      description: "",
      dcouments: [],
      fee: 2100,
      price: 2478,
    },
    "ANY NGO INCOME RELATED QUERY": {
      subSections: null,
      description: "",
      dcouments: [],
      fee: 2100,
      price: 2478,
    },
  },
  filing: {
    "ITR-1": {
      subSections: null,
      description:
        "Salaried Employee / Pensioner with Income from Other Sources",
      dcouments: [],
      fee: 1100,
      price: 1298,
    },
    "ITR-2": {
      subSections: null,
      description:
        "Salaried Employee / Pensioner with Income from Other Sources and House Property Income",
      dcouments: [],
      fee: 1500,
      price: 1770,
    },

    "ITR-3": {
      subSections: null,
      description:
        "Salaried Employee / Pensioner with Income from Other Sources, House Property Income & Capital Gain other than Shares",
      dcouments: [],
      fee: 2100,
      price: 2478,
    },

    "ITR-4(Assessee with Professional Income and Income from Other Sources)": {
      subSections: null,
      description:
        "Assessee with Professional Income and Income from Other Sources",
      dcouments: [],
      fee: 1500,
      price: 1770,
    },
    "ITR-4(Assessee with Professional Income as well as House Property and Income from Other Sources)":
      {
        subSections: null,
        description:
          "Assessee with Professional Income and Income from Other Sources",
        dcouments: [],
        fee: 2100,
        price: 2478,
      },
    "ITR-4(Assessee with Professional Income as well as House Property, Capital Gain and Income from Other Sources)":
      {
        subSections: null,
        description:
          "Assessee with Professional Income and Income from Other Sources",
        dcouments: [],
        fee: 4100,
        price: 4838,
      },
    "ITR-5": {
      subSections: null,
      description:
        "Assessee with Professional Income as well as House Property and Income from Other Sources",
      dcouments: [],
      fee: 2100,
      price: 2478,
    },

    "ITR-6": {
      subSections: null,
      description:
        "Assessee with Business Income as well as House Property and Income from Other Sources",
      dcouments: [],
      fee: 5100,
      price: 6018,
    },
    "ITR-7": {
      subSections: null,
      description:
        "NGOs / SOCIETIES / TRUST / CHARITABLE COMPANIES WITH INCOME TAX EXEMPTION APPROVAL",
      dcouments: [],
      fee: 7100,
      price: 8378,
    },
    "TDS QUARTERLY RETURNS - 24 - Q1, Q2 & Q3": {
      subSections: null,
      description: "",
      dcouments: [],
      fee: 2100,
      price: 2478,
    },
    "TDS QUARTERLY RETURNS - 24 - Q4": {
      subSections: null,
      description: "",
      dcouments: [],
      fee: 4000,
      price: 4720,
    },
    "TDS QUARTERLY RETURNS - 26 - Q1, Q2, Q3 & Q4": {
      subSections: null,
      description: "",
      dcouments: [],
      fee: 2100,
      price: 2478,
    },
    "TCS QUARTERLY RETURNS": {
      subSections: null,
      description: "",
      dcouments: [],
      fee: 2100,
      price: 2478,
    },
    "CORRECTION IN TDS / TCS STATEMENTS": {
      subSections: null,
      description: "",
      dcouments: [],
      fee: 1100,
      price: 1298,
    },
    "TDS ON SALE OF PROPERTY -CHALLAN CUM RETURN": {
      subSections: null,
      description: "",
      dcouments: [],
      fee: 5100,
      price: 6018,
    },
    "REFUND MATTERS FOR EXCESS TDS / TCS DEPOSIT": {
      subSections: null,
      description: "",
      dcouments: [],
      fee: 5100,
      price: 6018,
    },
  },
};

const FixMyTaxServiceType = {
  GST_Notice: 1,
  ITR_TDS_TCS_Notice: 2,
  ITR_TDS_TCS_Filing: 3,
  Consultation: 4,
};

const ServiceType = {
  VideoConsultation: 1,
  NoticeReply: 2,
};

export {
  FixMyTaxServiceType,
  fixMytaxServiceInfoData,
  fixMytaxServicesInfo,
  ServiceType,
};
