
version: '3.7'

services:
  postaltrackingbackend:
    image: postaltracking.azurecr.io/postalbag-backend:20221003-1
    environment:
      ASPDOTNETCORE_Environment: "Production"
      ASPNETCORE_URLS: "https://+;http://+"
      Kestrel__Certificates__Default__Password: "#yperGr!d!@#"
      Kestrel__Certificates__Default__Path: "/app/zupiers.pfx"
    restart: always
#    volumes:
#      - type: bind
#        source: C:\Users\Puneet Mathur\zupiers\PostalBagTracking\zupiers.pfx
#        target: /app/zupiers.pfx
    ports:
      - 80:80
      - 443:443